### ISSUE TITLE
Reduce the number of languages on the language filter drop down

### ISSUE THREAD

**Issue by allisonnorman** [18F/samhsa-prototype#121]
findtreatment.samhsa.gov has a consolidated list of languages. Given that many of the languages don't seem to correspond to facilities that speak that language, and the overwhelming long list that we have today, I propose that we reduce our filter dropdown options to match (for now) what SAMHSA is currently using (see below). 

Alternatively, if we could make language configurable like the other filter options, we could allow easy addition/subtraction of language filter options in the future. 

- Spanish
- Arabic
- Any Chinese Language
- Creole
- Farsi
- French
- German
- Greek
- Hebrew
- Hindi
- Hmong
- Italian
- Japanese
- Korean
- Polish
- Portuguese
- Russian
- Tagalog
- Vietnamese
(American Indian Languages)
- Hopi
- Lakota
- Navajo
- Ojibwa
- Yupik
- Lakota

**Comment by hursey013** [comment]
Right now the language list is populated from an API call to a `/languages` endpoint that returns a current list of the languages from the database. I'm guessing the initial options that are shown on the current locator are somehow handpicked, because they aren't designated in any special way in the API response. 

If we have a curated list like the one above, do we just not display the other language options, or how would that work?

**Comment by allisonnorman** [comment]
Other ideas from our backlog doc:
- Search by language 
- From BL: is there a way to hide language so when you click it, you would have to click something like "see more" if you wanted to really get to languages like Samoan or whatever as an example

**Comment by hursey013** [comment]
@allisonnorman are we sure this is even a problem right now? Yes the list is long, but it doesn't feel unmanageable to me. I'd say if someone were to be adding multiple languages we'd want a different interaction, but since we are limited to just choosing one, even with a long list it seems like I can generally select any of the options pretty quickly.

**Comment by allisonnorman** [comment]
No, we're not sure this is a problem. Just trying to capture all of our backlog items in issues for prioritization, rather than the doc. My concern is less the UX of selecting a language, but that many of the languages don't have any facilities associated with them, and some even seem like duplicates (maybe because of how they were entered in the survey). This may be something we just keep an eye on and put on a longer term roadmap.

**Comment by bpdesigns** [comment]
From ONE person, but adding to this issue for relevancy

> "Language selection does not include Somali.  Minnesota has the largest population of Somalians in the Country, with over half million residents."

**Comment by bpdesigns** [comment]
In one interview we had someone who went through the language filter and **was looking for "English" on the list.**

**Comment by hursey013** [comment]
Yeah I noticed this as well, it does feel odd to not include `English`, but I guess the presumption is that they all offer English and choosing another language is in addition to English, but that doesn't really translate very well to the end user in the current interaction.

**Comment by hursey013** [comment]
Resurfacing this one @allisonnorman - this will need to happen for MVP because it generates an API request.
