### ISSUE TITLE
Improve visual design of info section

### ISSUE THREAD

**Issue by allisonnorman** [18F/samhsa-prototype#223]
Once we've landed on a visual design concept, we should incorporate some of those elements in the info section (https://findtreatmentbeta.18f.gov/content/what-to-expect). 

Some ideas from @amandacostello: 
- Different treatment for H3s (#235) - Sections should pop more
- Move content into separate pages (#236) 

Some ideas we've thrown around:
- Add 'back to top"
- Consider incorporating images
- Think more about the length of the content (keep using jump links or load content in for each section separately?)
- Add scroll spy to content page navigation #131
- Add polyfill for position:sticky #140

**Comment by allisonnorman** [comment]
Assigning to Amanda first to give content feedback before we hand over to design

**Comment by amandacostello** [comment]
Here's the breakdown of how the info content will be broken down page by page (HRs in doc representing new pages): https://docs.google.com/document/d/1XXwHJawxTD_okOq0oDyBGpiHN1-zIT33izWqfyG5LSM/edit#

**Comment by austinhernandez** [comment]
### How it should work:
- This mockup combines all the elements @amandacostello, @allisonnorman, and I talked about in co-working 9/3 
- Each sub-navigation item will have it's own page instead of mega-long anchor linked page.
  - This way, either the header or footer is quickly visible when you go to the page.
- There will be no back button. I was thinking this opened in a new tab or window so your search results are right where you left them. 
  -  The tooltips in issue #218 help provide more info in context!
- Optional: Much like the "report a problem with this listing" button on the bottom of the facility details page, I added a "is this helpful?" question at the bottom, as a way to assess which pages need attention. Remove if out of scope.

### Example page: 
![image](https://user-images.githubusercontent.com/23194720/64202640-a3fd1d00-ce5f-11e9-8079-519d9c986a71.png)

### Content
Amanda's content ([Here](https://docs.google.com/document/d/1XXwHJawxTD_okOq0oDyBGpiHN1-zIT33izWqfyG5LSM/edit#)) is laid out the way it should appear in the site  


### Sketch file
[On Drive in the UI folder - samhsa-mobile-desktop-pages9-2](https://drive.google.com/drive/folders/1rgFoIgnyOb_JsxIE5uK1eMSRdl3Q0E0E)

**Comment by allisonnorman** [comment]
Resolved in #269
