### ISSUE TITLE
Different treatment for H3s

### ISSUE THREAD

**Issue by amandacostello** [18F/samhsa-prototype#235]
The current H3 headers blend in a lot with the body text, making it hard to scan through content. Could these be a different font/color/style? 

(Also, this problem may go away when we move the content sections to their own pages, but wanted to drop this here so I don't forget.)

**Comment by Jkrzy** [comment]
@amandacostello since we're moving forward ahead w/ the content as-is lets look at lightweight options here.

Is underlining the `H3` text an adequate stopgap?

---
<img width="629" alt="Screen Shot 2019-08-21 at 9 30 58 AM" src="https://user-images.githubusercontent.com/3485564/63436418-aa6aae00-c3f6-11e9-8d34-218b2114eea8.png">

---

<img width="276" alt="Screen Shot 2019-08-21 at 9 32 26 AM" src="https://user-images.githubusercontent.com/3485564/63436447-b5254300-c3f6-11e9-85d6-1d625d884bc0.png">

**Comment by allisonnorman** [comment]
Closing as I've consolidated the info content asks into one issue: #223
