### ISSUE TITLE
Direct to Helpline if javascript is disabled

### ISSUE THREAD

**Issue by Jkrzy** [18F/samhsa-prototype#327]
Let's expand this to include more details about why Javascript needs to be enabled and encourage visitors to call the helpline if they're unable to access the site.

_Originally posted by @Jkrzy in https://github.com/18F/samhsa-prototype/pull/269/review_comment/create_

**Comment by hursey013** [comment]
Additional context: https://github.com/18F/samhsa-prototype/pull/269/files#r325638436

**Comment by allisonnorman** [comment]
**Needed for MVP**: Revised messaging to point visitors to the helpline if javascript is not enabled

Taking a look at the PR, this is what it currently says: "You need to enable JavaScript to run this app." The ask from @hursey013 in that PR is here: https://github.com/18F/samhsa-prototype/pull/269/files#r325638436

**Comment by amandacostello** [comment]
Added the content in the PR!

**Comment by allisonnorman** [comment]
Thank you, @amandacostello! That PR has been merged and the comment could get lost in the shuffle so let's keep this open to track the change. 

From @amandacostello: 

Text for folks who don't have JavaScript turned on

**Please turn on JavaScript for your browser**
This site uses JavaScript, a programming language that runs on your web browser.
You're seeing this message because JavaScript is currently turned off or disabled for your browser. This site uses JavaScript to search for and show treatment facilities.

To use this site, please turn on or enable JavaScript in your browser's settings. This is often found in the Security or Privacy settings.

You can always call the HelpLine to talk to a person who can help you find treatment options. They're available at 1-800-662-HELP (4357).
