### ISSUE TITLE
Refactor `location` field from a filter to it's own slice of form state

### ISSUE THREAD

**Issue by el-mapache** [18F/samhsa-prototype#41]
Currently, the `location` field is used in both the `homepage` form and the `filters` form. Since it is the only required piece of data, and is not treated the same as other filters, we should refactor it into it's own slice of `redux-form` state in order to more cleanly share the data between views.

**Comment by hursey013** [comment]
Right now I'm saving the whole response from the google places API, and all we need at the moment is the location label and geocoordinates. Is there any advantage to just saving those things to the store, or is ok to just continue saving the entire object?

**Comment by el-mapache** [comment]
I think its slightly better practice to just request / store the fields that we need, but if it isn't causing any immediate issues I'm not sure we need to make changes yet.

**Comment by hursey013** [comment]
Rather than storing the location in both the homepage and filter forms, it is now only stored in the filters form eliminating the need to share the values back and forth. This eliminates the risk that the values could become out of sync between forms.

Should we want to further separate the location from the filters to improve the user experience we should re-open this to split `location` off into it's own state.
