### ISSUE TITLE
Make outbound links open in a new tab. 

### ISSUE THREAD

**Issue by bpdesigns** [18F/samhsa-prototype#494]
### Current State
- search for treatment 
- click on a link in the footer that brings you to a different site
- click the back button
- your search is removed. 

### Desired State (updated)
- Make external/outbound links open in a new tab. 

### Reason
- avoids people losing their search
- footer content is outside of the experience of the site.

**Comment by bpdesigns** [comment]
@allisonnorman @Jkrzy I think this should be a easy switch that will improve the experience for people

**Comment by bpdesigns** [comment]
I'd also make the header links open in a new tab

We are testing a new design for our substance use treatment locator. Have feedback? **We want to hear from you.**
Visit the current site at **findtreatment.samhsa.gov**

**Comment by bpdesigns** [comment]
Annnnnd any links in the content pages that go to a new site_  they should also **open in a new tab** for the same reason stated above. (Note: links to internal site content should always open in the _same_ window and not a new one. 

The only place I'm seeing this in a quick scan is:
- If you’ve been denied coverage for treatment, this **Mental Health and Addiction Insurance Help** tool can help you find the right resources to solve issues with your insurance. 

@amandacostello if there are other links to outside resources from the content pages.

**Comment by allisonnorman** [comment]
I am pretty sure we made a decision earlier on to not open up new tabs for any external links, as it makes a choice on behalf of the visitor and standard practices are to not do that. I could see making an exception for the feedback form but otherwise, I think we should be consistent with what we decided before, unless we have a reason not to follow that standard.

**Comment by bpdesigns** [comment]
Agreed. The reason I wrote the comment is that searches are lost if you exit the site then reenter it from the back button. I think will disruptive for people. I'm not sure if this was always the case with the site. If it is, I'm sorry I overlooked it til now :(

**Comment by allisonnorman** [comment]
No need to be sorry! I'm just weary of making changes, even small ones, given how close we are to launching.

@davemcorwin - Just curious. Is there a way to universally change this for external links or would it be manual? What do you think about this?

**Comment by davemcorwin** [comment]
Right now we are opening the Google map links in a new tab, but I think that's it. As @allisonnorman mentioned, if the user navigates away from the site we lose the search even if they hit the back button since the data is only stored in memory.

@allisonnorman I can make a change to be able to make a universal change :) That is, I can change the component we are using for all external links so it would be the default behavior as opposed to adding `target="_blank"` everywhere...

Alternatively, we can make enhancements to enable the search to be retained via the "back" button for users who navigate away.

The latter is definitely more work and potentially more risky but doable in the timeframe that we have.

**Comment by bpdesigns** [comment]
Totally understand not wanting to change anything too much at this state @allisonnorman :) 

I think this could wait til after launch but would want to prioritize it as high after that. 

Two links I would manually change to open in a new tab now if there is time are:
1. The link to the feedback form at the top of each page
2. The link to the "Mental Health and Addiction Insurance Help" tool. Since paying for treatment is a large factor for people, I'd imagine people would want this open as they in the middle of their search

**Comment by allisonnorman** [comment]
Universally changing the external links to target = blank seems to be the easiest option and I'm fine with that, especially if you think reduces barriers for the audience, @bpdesigns.

@davemcorwin - I know you have a lot going on with documentation, but do you think this is feasible in the next couple days? I think we should just make the change in prod rather than making it on the launch prep branch.

**Comment by davemcorwin** [comment]
Both options:
1. changing the 2 links that @bpdesigns suggested
2. universally changing all of them

are low-lift and low-risk, and can be done today.

**Comment by allisonnorman** [comment]
Great. Let's go with #2.  I updated the issue for this.
