### ISSUE TITLE
Resolve 404 issues

### ISSUE THREAD

**Issue by allisonnorman** [18F/samhsa-prototype#507]
From testing FindTreatment.gov, we saw that 404s aren't working properly for URLs that don't exist.

Dave's digging into options around this, specifically:
1. [x] 404 pages not rendering correctly
2. [x] 404 error page showing up for direct link facility pages
3. [X] 404 language in facility page preview renderings (update meta tags and link?)~ Resolved in #505 / #506

**Comment by davemcorwin** [comment]
The first item has been resolved for `findtreatmentbeta.18f.gov` by asking Federalist/Cloud.gov to return our generated 404.html for 404s instead of returning the index.html, which as previously required when we did NOT statically render anything. I have a request in to address this for `findtreatment.gov` as well.

The second item is a bit of a catch-22. The application is a mix of static and dynamic pages and we do not have the ability to control 404 behavior by path, so anytime a user requests a page (by URL NOT by link in the application), the server will return the statically rendered page if it exists, or 404.html if it does not.

This is problematic for dynamic pages where they do not exist on the server, but do exist within the context of the running application, resulting in the user seeing a 404 page until the application fully boots up. This is not the greatest UX and is especially disconcerting on slower connections where the user will see the 404 for a while until the app boots up.

In practice, this affects the facility pages on refresh OR if a facility url were to be shared and someone clicks the direct link. The only option of which I can think to improve this is to statically render ALL of the facility pages. This is possible and there are a couple of ways to actually do it, would like to chat with the group on this issue to see how we want to proceed.

**Comment by davemcorwin** [comment]
Update: Cloud.gov replied that they have updated the configuration for findtreatment.gov, will verify this afternoon.

**Comment by amandacostello** [comment]
For facility page, just display the `Loading` dot circle (same one that shows while running a search). 

If loading times are a consistent issue post-launch, add in the following content below the `Loading` dot circle:

A lot of people are using the locator right now, and pages are loading slower than usual. If you don't want to wait for this to load, call SAMHSA's national helpline at 1-800-662-HELP (4357). Helpline staff are available 24/7 and can help you with treatment information and referrals.

**Comment by davemcorwin** [comment]
This is resolved!!!
